In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
arr1.shape

(5,)

In [5]:
arr1.dtype

dtype('int64')

In [6]:
arr1.ndim

1

In [4]:
arr2 = np.array([[1,2,3], [4, 5, 6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2.dtype

dtype('int64')

In [7]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 3)

In [11]:
arr2.size

6

In [15]:
arr2.flatten()

array([1, 2, 3, 4, 5, 6])

In [16]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [29]:
arr3 = np.array([[1,2,3,5,6,7], [3,4,5,6,7,12]])

In [33]:
arr3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 3,  4,  5],
        [ 6,  7, 12]]])

In [34]:
###### Matrix

In [37]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.matrix(arr2)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [38]:
mat2 = np.matrix(arr2)

matrix([[1, 2, 3, 4, 5, 6]])

In [44]:
m= np.matrix('1 2 4; 4 5 6')

In [45]:
m

matrix([[1, 2, 4],
        [4, 5, 6]])

In [46]:
mat2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [47]:
np.min(mat2)

np.int64(1)

In [48]:
np.sum(mat2)

np.int64(21)

In [49]:
np.mean(mat2)

np.float64(3.5)

In [50]:
np.std(mat2)

np.float64(1.707825127659933)

In [51]:
np.diag(mat2)

array([1, 5])

In [60]:
mat2 = np.matrix(np.array([[1,2,3], [4,5,6]]))
mat3 = np.matrix(np.array([[10,20,30], [40,50,60]]))

In [61]:
mat2 + mat3

matrix([[11, 22, 33],
        [44, 55, 66]])

In [62]:
mat3 - mat2

matrix([[ 9, 18, 27],
        [36, 45, 54]])

In [63]:
mat2 * mat3

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [64]:
mat2 = np.matrix(np.array([[1,2,3], [4,5,6]]))
mat3 = np.matrix(np.array([[10,20,30], [40,50,60], [60, 70, 80]]))

In [65]:
mat2 * mat3

matrix([[270, 330, 390],
        [600, 750, 900]])