In [1]:
from array import *

In [2]:
arr = array('i', [1,2,3],[4,5, 6])

TypeError: array() takes at most 2 arguments (3 given)

In [8]:
from  numpy import *

In [9]:
arr = array([1,2,4,5,79,9])

In [10]:
arr

array([ 1,  2,  4,  5, 79,  9])

In [28]:
# array()
# linspace()
# logspace()
# arange()
# zeros()
# ones()

In [11]:
arr.shape

(6,)

In [12]:
arr.tolist()

[1, 2, 4, 5, 79, 9]

In [13]:
arr.argmax()

np.int64(4)

In [14]:
arr.max()

np.int64(79)

In [15]:
arr.argsort()

array([0, 1, 2, 3, 5, 4])

In [18]:
import numpy as np

In [19]:
np.arange( 1, 5, 1)

array([1, 2, 3, 4])

In [20]:
np.arange( 10 )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
type(np.arange( 10 ))

numpy.ndarray

In [22]:
# Convert all values into float
array([0, 1, 2, 3, 5.0, 4])

array([0., 1., 2., 3., 5., 4.])

In [23]:
# Convert all values into string
array([0, 1, 2, 3, "5.0", 4])

array(['0', '1', '2', '3', '5.0', '4'], dtype='<U21')

In [25]:
# Convert all values into float
array([0, 1, 2, 3, 5.2, 4],int)

array([0, 1, 2, 3, 5, 4])

In [31]:
# Linspace breaks values in to number of chunks

In [32]:
linspace(0, 25, 3)
#Linear

array([ 0. , 12.5, 25. ])

In [33]:
arange(0, 25, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [34]:
logspace(1, 40, 5)
#Logarithmic

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

In [37]:
zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])