In [3]:
import numpy as np

In [4]:
arr1 = np.array([1,3,5,7])

In [5]:
arr2 = np.array([2,4,6,8])

In [6]:
arr1 + arr2

array([ 3,  7, 11, 15])

In [7]:
arr1 + 5

array([ 6,  8, 10, 12])

In [8]:
print(np.log(arr1))

[0.         1.09861229 1.60943791 1.94591015]


In [9]:
print(np.sqrt(arr1))

[1.         1.73205081 2.23606798 2.64575131]


In [10]:
print(np.sum(arr1))

16


In [11]:
print(np.min(arr1))

1


In [12]:
print(np.max(arr1))

7


In [13]:
print(np.mean(arr1))

4.0


In [14]:
print(np.median(arr1))

4.0


In [15]:
print(np.std(arr1))

2.23606797749979


In [16]:
arr1

array([1, 3, 5, 7])

In [18]:
print(np.concatenate([arr1,arr2]))

[1 3 5 7 2 4 6 8]


In [19]:
arr3 = arr1

In [22]:
print(id(arr1), id(arr2), id(arr3))

132243250868080 132243327633328 132243250868080


In [23]:
arr1[1] = 100

In [24]:
arr1

array([  1, 100,   5,   7])

In [26]:
arr3
# Shallow copy

array([  1, 100,   5,   7])

In [28]:
#Deep COpy
arr1

array([  1, 100,   5,   7])

In [29]:
arr4 = arr1.copy()

In [30]:
arr4

array([  1, 100,   5,   7])

In [31]:
print(id(arr1), id(arr4))

132243250868080 132242430813136


In [32]:
arr1[1] = 200

In [33]:
arr1

array([  1, 200,   5,   7])

In [35]:
arr4

array([  1, 100,   5,   7])